# Generated by Django 3.1.4 on 2021-02-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210207_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSingleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.BooleanField(verbose_name='author')),
                ('comment', models.BooleanField(verbose_name='comment')),
                ('allow_discussion', models.BooleanField(default=True, verbose_name='allow discussion')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_single_setting', related_query_name='product_single_setting', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ProductSingleSetting',
                'verbose_name_plural': 'ProductSingleSettings',
            },
        ),
    ]
