# Generated by Django 3.1.4 on 2021-02-28 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210228_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlike',
            name='condition',
            field=models.BooleanField(default=True, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='productlike',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlike',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update at'),
        ),
    ]
