# Generated by Django 3.1.4 on 2021-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210228_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='', verbose_name='Image'),
        ),
    ]
