# Generated by Django 3.1.4 on 2021-01-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=256, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='site/slideshow', verbose_name='BackGround')),
                ('action_text', models.CharField(max_length=20, verbose_name='action text')),
                ('action_url', models.URLField(verbose_name='action url')),
            ],
        ),
    ]
