# Generated by Django 3.1.4 on 2021-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='action_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='action url'),
        ),
    ]
