# Generated by Django 3.1.4 on 2021-02-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_commentlike'),
        ('order', '0003_auto_20210212_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketItems',
            new_name='BasketItem',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
