# Generated by Django 3.1.4 on 2021-02-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210212_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='TotalPrice'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.basket', verbose_name='Basket'),
        ),
    ]
