# Generated by Django 3.1.4 on 2021-02-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210212_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
