# Generated by Django 3.1.4 on 2021-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_basketitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
