# Generated by Django 3.1.4 on 2021-02-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_date_created'),
        ('order', '0011_order_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='shop_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_item', related_query_name='basket_item', to='product.shopproduct', verbose_name='Shop Product'),
        ),
    ]
